server:
  port: 8081

logging:
  level:
    root: info

spring:
  dubbo:
    application: manage-web
    protocol:
      name: dubbo
    registry:
      address: 192.168.171.132:2181
      protocol: zookeeper
    base-package: com.atguigu.gmall #扫描
    consumer:
      timeout: 60000 #设置超时时间
      check: false #设置是否检查服务存在
