#服务端口号
server:
  port: 8070
#JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/gmall_study?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  #dubbo配置
  dubbo:
    application: user-service
    protocol:
      name: dubbo
    registry:
      address: 192.168.171.132:2181
      protocol: zookeeper
    base-package: com.atguigu.gmall


#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml   #扫描mapper文件
  configuration:
    map-underscore-to-camel-case: true    #转成驼峰命名


#日记级别  打印sql语句
logging:
  level:
    root: info

#通用mapper
mapper:
  identity: MYSQL
